spring:

  application:
    name: messaging-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SEND_FROM_MAIL}
    password: ${SEND_FROM_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
    consumer:
      group-id: messaging
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.type.mapping: >
          receipt:com.softserve.messaging.model.UserReceipt,
          validation:com.softserve.messaging.model.UserValidation

service-token: ${SERVICE_TOKEN}

