spring:
  datasource:
    initialization-mode: always
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
    change-log: classpath:/database/changelog-master.xml
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: receipt:com.softserve.paymentservice.dto.InvoiceDto
stripe:
  public-key: ${STRIPE_PUBLIC_KEY}
  private-key: ${STRIPE_SECRET_KEY}
