spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: ${BOOTSTRAP_SERVERS}
      group-id: trip
      properties:
        spring:
          json:
            type:
              mapping: status:com.softserve.kickscootertrip.dto.ScooterStatusDto
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

payment-url: ${PAYMENT_URL}
vehicle-url: ${VEHICLE_URL}